Updated documentation and Csv
MirzaBaig715/WeatherData pull request #2
Opened 2017-03-05 21:32 UTC by MirzaBaig715

Added documentation and correct errors.File Handling with CSV.

2017-03-06 12:30 UTC, sadan requested changes

2017-03-06 12:30 UTC, sadanarshad commented on weatherman.py
> +path = "*.txt"
What is this? This is not complete path of the weather files i guess

2017-03-06 12:30 UTC, sadanarshad commented on weatherman.py
> +            lines = csv.reader(f)
use CSV dict reader to extract data from files. That will refactor and improve your logic more.

2017-03-06 12:30 UTC, sadanarshad commented on weatherman.py
> +          str("MAXTemp").rjust(7),
this is good.

2017-03-06 13:57 UTC, MirzaBaig715 commented on weatherman.py
> +          str("MAXTemp").rjust(7),
That's Great ! Thanks

2017-03-06 13:57 UTC, MirzaBaig715 commented on weatherman.py
> +            lines = csv.reader(f)
Yes i will extract using DictReader. Will also make it more memory efficient. Thanks for reviewing.

2017-03-06 13:59 UTC, MirzaBaig715 commented on weatherman.py
> +path = "*.txt"
files are in current Project Directory. We just have to extract _*.txt_ files from folder.

2017-03-09 03:21 UTC, sadanarshad commented on weatherman.py
> +        MAXTemp = []
variable name are always written in small letters **max_temp**, unless some sort of global or settings variable written in all caps.

2017-03-09 07:21 UTC, sadan approved these changes

2017-03-09 16:56 UTC, merged